lang: cpp
compiler:
    - clang
before_script:
    - add-apt-repository ppa:geoarge-edison55/cmake-3.x
    - apt-get update
    - apt-get install cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

