lang: cpp
sudo: required
compiler:
    - clang
before_install:
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get -y update
install:
    - sudo apt-get -y install cmake
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - make
after_success:
    - make test

