lang: cpp
sudo: required
compiler:
    - clang
before_install:
    - mkdir build
    - pushd build
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar -zxf cmake-3.2.3-Linux-x86_64.tar.gz
    - cmake-3.2.3-Linux-x86_64/bin/cmake --version
    - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - sudo add-apt-repository -y 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get -y -qq update
    - sudo apt-get install clang-3.6
    - export CXX="clang++-3.6"
before_script:
    - cmake-3.2.3-Linux-x86_64/bin/cmake .. 
script:
    - make
after_success:
    - make test

