lang: cpp
sudo: required
compiler:
    - clang
before_script:
    - sudo add-apt-repository ppa:geoarge-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

