lang: cpp
sudo: required
compiler:
    - clang
before_install:
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
    - echo "y" | sudo sh cmake-3.2.3-Linux-x86_64.sh
    - cmake --version
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - make
after_success:
    - make test

