lang: cpp
sudo: required
compiler:
    - clang
before_install:
    - mkdir build
    - pushd build
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar -zxf cmake-3.2.3-Linux-x86_64.tar.gz
    - cmake-3.2.3-Linux-x86_64/bin/cmake --version
before_script:
    - cmake-3.2.3-Linux-x86_64/bin/cmake ..
script:
    - make
after_success:
    - make test

