= Техническое задание на разработку
Павел Филонов <filonovpv@gmail.com>
Версия 1.0 черновик 1 
:toc:
:numbered:

== Введение

=== Назначение документа
В данном документе описаны технические требования к разработке приложения syslog-amqp. Текущая версия документа имеет номер 1 и является черновой.

=== Условные обозначения
При ссылке не описанную в документе функциию используется выделение жирным шрифтом. Например, в соответствии с функцией *Генерация уникальных идентификаторов*...

=== Целевая аудитория и рекомендации по работе с документом

Данный документ предназначен для ознакомления потенциальных работодателей с навыками автора по составлению технического задания в соответствии с шаблоном из стандарта IEEE 830, описанного в [1]. Использованные здесь примеры оформления также могут быть полезны начинающим разработчикам и аналитикам.

Для быстрого ознакомления с основными сценариями использования следует в первуюю очередь изучить раздел <<product_features, функции продукта>> и <<appendix-b, приложение Б>>. Для более детально ознакомления с возможностьми прилоежния следует обратить внимание на раздел <<system-features, функции системы>>.

=== Содержание и границы проекта

В рамках проекта предлагается разработать прилоежние для приема логов в формате syslog и отправке их в брокер системы сообщений RabbitMQ. Основная _цель проекта_ - подготовить пример портфолио автора, на основе которого можно было бы продемонстрировать такие навыки как:

    * составление технического задания;
    * подготовка проектной документации;
    * составление плана тестирования;
    * разработка программного обеспечения;
    * автоматизация интеграционных и функциональных тестов;
    * оформление рабочей документации.

В качестве побочных целей выступают осовение новых подходов и инструментов для разработки, тестировани и верстки документации.

=== Ссылки

. Karl E. Wiegers "Software Requirements", 2-n edition, ISBN: 9780735618794, 2003
. Описания стандарта syslog https://tools.ietf.org/html/rfc5424[RFC 5424]
. Передача syslog сообщений поверх UDP https://tools.ietf.org/html/rfc5426[RFC 5426]
. Передача syslog сообщений поверх TLS https://tools.ietf.org/html/rfc5425[RFC 5425]
. Передача syslog сообщений поверх TCP https://tools.ietf.org/html/rfc6587[RFC 6587]
. Описание стандарта UUID https://www.ietf.org/rfc/rfc4122.txt[RFC 4122]
. Описание стандарта ISO8601 https://www.ietf.org/rfc/rfc3339.txt[RFC 3339]
. Коллектор syslog сообщений https://syslog-ng.org[syslog-ng]
. Система сбора логов http://logstash.net[logstash]
. Syslog сенсор http://www.opennet.ru/man.shtml?topic=syslogd&category=8[syslogd]

== Общее описание

=== Перспективы продукта
Ближайшими аналогами разработываемого прилоежения являются программы *apache flume*, *syslog-ng* и *logstash*. Все
упомянутые приложения предназначены для решения задачи аггрегации, обработки и пересылки лог сообщений для последующего хранения и
анализа. Данный класс приложений черезвычано востребован в системах, решающих задачи из области Log Management. Разрабатываемое
в рамках данного проекта приложение является абсолютно новым с точки зрения кодовой базы, но заимствует некоторые идеи и
подходы от своих аналогов.

[[product_features]]
=== Функции
В основные функции приложения входят:
 * аггрегация лог сообщений от различных сетевых источников
 * обогащение сообщений дополнительной информацией (время, источник, метки и проч)
 * пересылка сообщений в брокер очередей RabbitMQ для дальнейшей обработки

// TODO: добавить картинку

=== Классы пользователей и характеристики

Следует выделить два основных класса пользователей данного продукта:

 * специалист по информационной безопастности (ИБшник)
 * системный администратор (Админ)

Роль ИБшника заключается в планировании схемы развертывания продукта внутри сетевой инфраструктуры.
Роль Админа заключается в настройке прилоежния, мониторинге его активности и анализу причин отказов.

=== Рабочее окружение

Данное прилоежние будет функционировать на сетевых серверах под управление ОС семейства GNU/Linux и использовать в
качестве сетевого стека TCP/IP на основе протокола IPv4.

=== Ограничения на дизайн и реализацию
 * обязательно поддержка работы на ОС GNU/Linux
 * обязетально поддержка брокера очередей RabbitMQ
 * обязетально поодержка сбора сообщений посредством протокола UDP
 * в соответствии со стандартом [...] недопускается вносить изменений в содержимое принятых сообщений

=== Пользовательская документация

Для Админов необходимо предоставить документацию по настройке и мониторингу прилоежния.
Предпочтительно иметь пример файла с настйроками, в котором в виде комментариев подробно описаны
все поддерживаемые прилоежнием настройки. Также необходимо иметь справку об опциях командной строки, которая будет
выводиться самим прилоежнием при запуске с опцией '-h'.

[[system-features]]
== Функции системы

=== Прием сообщений

==== Описание и важность

Необходимо обеспечить прием лог сообщений по сети от источников. Данная функция имеет _высокую_ важность.

==== Описание цепочки запрос/ответ

Источник сообщения отправляет его по сети на заранее указанный адрес и порт, на котором должно работать настроенное
приложение. Приложение принимает все сообщение и отправляет его на обработку.

==== Функциональные требования

Необходимо поддерживать следующие сетевые протоколы

* UDP

Необходимо поддерживать сообщения максимально допустимой для UDP длинны. Для сообщений полученных по данному протоколу
необходимо проставлять метку *udp*. Предполагается, что в одной дейтаграмме приходит одно сообщение, даже если внутри
присутствуют переносы строк. Необходимо иметь возможность в настройках приложения указать адрес сетевого интерфейса, на
котором необходимо принимать дейтаграмма, а также номер порта. Необходимо поддерживать специальный адрес *0.0.0.0* - как
обозначение того, что следует принимать дейтаграммы с любого интерфейса.

=== Публикация сообщений

==== Описание и важность

Необходимо обеспечить публикацию принятых сообщений в брокер очередей RabbitMQ. Данная функция имеет _высокую_ важность.

==== Описание цепочки запрос/ответ

После получения нового сообщения его неоходимо опубликовать в описанном формате в обменник RabbitMQ.

==== Функциональные требования

Необходимо поддерживать протокол AMQP версии 0.9.1. Небходимо задавать через файл настроек следующие параметры

 * адрес RabbitMQ
 * порт RabbitMQ
 * имя exchange для публикации
 * имя ключа маршрутизации
 * тип обменика *fanout*, *direct* или *topic*

Перед отправкой сообщений необходимо убедиться, что обменник создан с флагом *durable = true*. Сообщения публиковать
со значением опции *DeliveryMode = 2 (non-persistent)*.
При отправке событий в RabbitMQ их необходимо кодировать в виде JSON документов со следующим списком полей

   * *uuid* - уникальный идентификатор сообщений, сгенерированный в соответствии с UUID4
   * *recv_time* - время получения собщений в формате ISO8601
   * *recv_host* - адрес узла - источника сообщения
   * *msg* - тело исходного сообщения
   * *tags* - список строк для обозначения меток
   * *headers* - словарь строк для служеного использования

.Пример
----
{
  "uuid": "504d84f9-e0d9-4690-9ddc-1ded9ca75de8",
  "recv_time": "2015-01-01T00:00:00Z",
  "recv_host": "10.0.0.1",
  "msg": "some log message",
  "tags": ["udp"],
  "headers": {
    "content_type": "text/plain"
  }
}
----

=== Требования к внешним интерфейсам

==== Пользовательский интерфейс

Приложение должно поддерживать интерфейс командной строки и запуск его со следующими параметрами

* *-h* - справка по параметрам командной строки
* *-v* - напечатать версию прилоежния и выйти
* *-c* - путь к конфигурационному файлу

==== Программные интерфейсы

 * поддержка брокера очередей RabbitMQ версий 3.4 и 3.5

==== Интерфейсы связей

 * поддержка приемы сообщений по протоколу IPv4

== Нефункциональные требования

=== Требования к производительности

Приложение должно обеспечивать публикацию сообщений с максимально возможной для RabbitMQ скоростью.
Для проведения приемочных испытаний предполагается использовать конфигурацию способную принимать 30000 сообщений в
секунду при среднем размере сообщений в 1 Кбайт. Пропусканая способность приложения не должна сильно деградировать
при увеличении числа источников. Оно должно функционировать с максимальной пропускной способностью при 1000 различных
источников.

При пропускной способности в 30000 eps приложение должно потреблять не более чем 10 % времени CPU (2,6 GHz Intel Core i5)
и не более чем 128 Мб RAM. Приложение не должно производить интенсивных дисковых операций чтения/записи.

=== Требования к безопастности

Для приложения не выдвигаются требования по безопастности.

=== Показатели качества программы

Прочие показатели качества отсутствуют.

== Прочие требования

=== Требования к логированию и мониторингу

Приложение должно вести собственный файл логов с поддержкой различных уровней логирования. Каждая запис лога
должна содержать метку времени и имя уровня логирования. Необходимо логировать версию приложения, опции запуска открытие
серверных сокетов и установление соединения с RabbitMQ. На уровне логирования *debug* необходимо логировать все установленные
клиентские сетевые соединения с указанием адреса и порта клиента.

Необходимо поддеривать логирование в файл, либо на стандартный поток ошибок. Путь к файлу с логом и уровень логирования должны
выставляться через файл настроек.


== Приложение А: Глосаррий

|===================
| syslog     | стандарт сетевого протокола передачи лог сообщений
| сенсор     | программа, которая регистрирует событие и оиправляет syslog сообщение
| коллектор  | программа, которая собирает данные в пасивном режиме с сенсоров
| TCP        | сетевой протокол транспортного уровеня с подтверждением доставки
| UDP        | сетевой протокол транспортного уровня без подтверждения доставки
| TLS        | криптографический сетевой протокол, работающий поверх TCP
| UUID       | стандарт идентификации
| ISO8601    | стандарт кодирования времени
|===================

[[appendix-b]]
== Приложение Б: Модели анализа

== Приложение В: Список вопросов
